### PR TITLE
Explaining that data are best on SQL server.

### PR DESCRIPTION
**Pull request by rtadd-git**
I have added some notes explaining the reasons not to store data in git repos.

**Review requests**
1. Please can you read my notes and let me know if there is anything unclear about them.
2. Do you disagree with anything I've written?
3. Do you have any other suggestions for good practice regarding data storage?
4. Can you think of a better place to put this section in the guidance? For me, choosing data storage is part of the project workflow but it's not quite consistent with the rest of the chapter which is more of an overview of git commands so I'd be interested in other perspectives on this.

### CODE REVIEW

**Review by cjrace — COMMENTED** [review]
Some general feedback from a team who use git in a lot of our workflows already.

1. Notes all make sense to me.

2. Agree with all the points made. I'd go even stronger on the size limitation, in my team we've had a repo become totally unusable because of storing too much data in it and over time the history built up and had to clear it, move everything to databases and start a new repository.

3. Another part of the workflow to consider around data storage is around the outputs of data and putting these into an outputs folder that is gitignore-d. So the source data is read in from wherever, and then all outputs are created into a folder that will never be committed. Would say it's worth making the distinction between source and output data so we cover both angles. 

Also if your code is in GitHub and public then any data stored in the repo will be too. Worth adding a note (or big flashy warning sign) here around making sure you only do this when the data is already published / appropriate for the public domain. 

If I remember correctly, GitHub has a limit of 100mb for files, so anything above that is an automatic no-no on the size front.

4. I've had a look through and it could possibly sit in a couple of other places, though I think I'd agree with having it here as this is the part of the guidance I'd be reading when asking the question to myself about data and the project setup. Interested to see the thoughts of a second reviewer on this too.

**Comment by rtadd-git** [comment]
@cjrace - thanks for the review, helpful comments. One thing I'd like to sense check with you:

> 3. Another part of the workflow to consider around data storage is around the outputs of data and putting these into an outputs folder that is gitignore-d. So the source data is read in from wherever, and then all outputs are created into a folder that will never be committed. Would say it's worth making the distinction between source and output data so we cover both angles.

If you gitignore your outputs, how do you manage the risk of different people having different copies of what they think are the same outputs locally? We tried gitignor-ing the .hmtl output from .Rmd files a couple of years ago and ended up in a mess with different people having different local versions and not realising.

[I do agree that saying something on outputs is a good idea.]

**Comment by rtadd-git** [comment]
@cjrace - helpful again thank you. I've now pushed some changes which I hope get into your comments.

Having reflected a bit more, I think our issue was that the .gitignore was set-up without all the team being properly in the loop so there were assumptions the .html file would be tracked and up to date and it wasn't. To cover this I've added a note about making sure the whole team are on the same page.

Also, in the process of writing about outputs I realised I really wanted to refer to tags so I thought I better add an explanation (at the end of the section). Grateful for any thoughts you have on this too.

**Comment by cjrace** [comment]
@rtadd-git sorry for the delay! The updates look good, I'm happy with that. 

The tagging section looks good too, it's something we've talked about using for a while in our area though we have never got around to doing them, with this guidance we might start as you've made it sound simple! Only thing to add might be a couple of lines on how to then roll back to a tag once you've made them - if you're in the terminal can you just checkout the tagged commit with a command?

**Comment by rtadd-git** [comment]
@cjrace - thanks again for another good suggestion. Content on how to get to the code you've tagged now added.

I really like tags and personally think they're surprisingly simple for the benefits they bring (which for us is saving far fewer output data files because we're confident we can go back and recreate them). I'd recommend giving them a go and happy to chat IRL if you'd like to see how we're using them.

**Review by cjrace — APPROVED** [review]

**Review by johalastrahol — COMMENTED** [review]
row 26 - where does it explicitly say in "Version Control Using Git - the basics" how you edit the git.ignore file. I couldn't find it in the original. 

row 126 - sisyphus - I presume we will remove this at some point. It was useful. I realised my previous comment regards merger was due to this change being the continuuation.

I agree with not copying data file - how shoudl we note that we can de-select pushing data files to DevOps - image would be useful. 

Image of where you find tag in DevOps would be useful.

**Comment by rtadd-git** [comment]
Thanks @johalastrahol.
* Useful comment about .gitignore files because it alerted me to a formatting issue in the live version I've missed. The content is there in the [section about merge conflicts](https://dfe-analytical-services.github.io/vsts-for-analysis/version-control-using-git-the-basics.html#merge-conflicts) preceded by ## but the heading hadn't formatted correctly. Looking at this, I think the issue was a lack of a space between the headling indicator (##) and the heading text (.gitignore). As such, I've been through and added spaces to headings in all files. Coming in the next push.
* On row 126 - can I clarify, would you prefer we keep or remove the wording about sisyphus?
* By "de-select pushing data files to DevOps", do you mean setting something on DevOps so we're not allowed to push files over a certain size?
* As with my other pull request, I think images need to be a separate task at the end so we do them all consistently and there is a task for this.

**Comment by johalastrahol** [comment]
@rtadd-git  
I meant that you can de-select file elements in R Studio Git pane for file that you want to "Push" to Azure DevOps.

> By "de-select pushing data files to DevOps", do you mean setting something on DevOps so we're not allowed to push files over a certain size?

Why is sisyphus in the document? Will it make sense when I knit the document together?
> On row 126 - can I clarify, would you prefer we keep or remove the wording about sisyphus?

**Comment by rtadd-git** [comment]
@johalastrahol:
* Reference to Sisyphus now removed as it is very much non-essential.
* Deselecting elements to push to git in RStudio I think means they aren't committed (as discussed last week, I'm not an RStudio git user) and this will cause problems if you want to change branch I believe so I'd prefer not to recommend this. If you have a fool proof way of doing this that I don't understand, we should have a chat.

**Review by johalastrahol — APPROVED** [review]
All OK now

**Pull request merged**
