### PR TITLE
Updating chapter 4 VSTS references to DevOps.

### PR DESCRIPTION
**Pull request by rtadd-git**
I have updated references to VSTS in chapter 4 to DevOps ones.
* Please check that I have updated all VSTS references to DevOps.
* Please check that I haven't changed anything else.
* Whilst you are looking at this chapter, please let me know if you think anything is unclear.

### CODE REVIEW

**Review by johalastrahol — APPROVED** [review]
Wording looks fine. I think we need pictures though  - to navigate around the operations in DevOps. Does this suggest developing the document in Word or something that can handle images. 

I think that is needs to be clearer where you are applying the git commands. I presume via Git Bash. But to the complete novice it makes no sense what git clone <project name>  etc. means. If you can use the command git push in DevOps - you need to show specifically where that can be done.

Row 97 - merge - is this dove tailing to another document as I think there needs to be more context how you merge.

Also - I think row 86 and 88 are duplicates.

**Comment by rtadd-git** [comment]
* We can include pictures here, see for example the out of date ones in the live version here: https://dfe-analytical-services.github.io/vsts-for-analysis/vsts-the-basics.html#pull-requests Updating pictures is a separate task because I think we need to do the whole document consistently in one go. There's a task on the planner board for this.
* Chapter 2 which comes before this it explains about git bash and merging. Git clone is not explained so I will add an explanation here - coming shortly.
* Yes, row 97 is a link to another section on merging once the whole document comes together.
* Rows 86 and 88 are not duplicates - 86 is a heading and 88 has the same text in a bullet point. However, I think the heading could be better so I will update this momentarially.

**Comment by rtadd-git** [comment]
@johalastrahol - I've made a couple of clarifications following your helpful comments. Please let me know whether or not they help.

**Review by johalastrahol — APPROVED** [review]
All OK

**Review by johalastrahol — APPROVED** [review]
All OK

**Pull request merged**
